
baseURL = "/"
title = "中国厨余堆肥网"
image = "images/logo.png"
theme = "twenty-twenty-hugo"
languageName = "En"
languageCode = "en-us"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here
# google analytics
googleAnalytics = "" # example : UA-123-45

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[permalinks]
posts = "/:year/:month/:title"

############################## Output ###############################
[outputs]
home = ["HTML", "RSS", "JSON"]

# unsafe html
[markup.goldmark.renderer]
unsafe = true

[taxonomies]
category = "categories"
tag = "tags"
author = "author"

############################## navigation ###############################

# main menu
[[menu.desktop]]
name = "可视化平台"
URL = "visual"
weight = 1

[[menu.desktop]]
name = "雪华说"
URL = "blog"
weight = 2

[[menu.desktop]]
name = "分级管理平台"
URL = "manage"
weight = 3

[[menu.desktop]]
name = "前言与案例"
URL = "preface"
weight = 4

[[menu.desktop]]
name = "论坛"
URL = "forum"
weight = 5

[[menu.desktop]]
name = "关于我们"
URL = "about"
weight = 6


#################### default parameters ################################
[params]

# cookies
[params.cookies]
enable = true
expire_days = 2

# banner
[params.banner]
heading = "中国厨余堆肥试点项目"
image = "images/2020-landscape-1-2.png"

# blog
# [params.blog]
# heading = "The premier destination for modern art in Northern Sweden. Open from 10 AM to 6 PM every day during the summer months."

# call to action
[params.call_to_action]
enable = false
title = "联系我们获取更多信息。"
content = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis"
button_label = "联系我们"
button_url = "contact"

# gallery
[params.gallery]
enable = true

[[params.gallery.gallery_item ]]
image = "images/2020-square-2.png"

[[params.gallery.gallery_item ]]
image = "images/2020-square-1.png"

# footer
[params.footer]
enable = false
title = "关于本网站"
content = "This may be a good place to introduce yourself and your site or include some credits."
address = "江苏省南京市溧水区秦淮大道288号"
copyright = "Copyright &copy; 2020 hugo theme"

[[params.links]]
name = "南京大学"
URL = "https://www.nju.edu.cn/"
weight = 1

[[params.links]]
name = "南京大学环境学院"
URL = "https://hjxy.nju.edu.cn/"
weight = 2

[[params.links]]
name = "南京大学自然资源研究院"
URL = "https://liee.nju.edu.cn/"
weight = 3

[[params.links]]
name = "生态环境部"
URL = "http://www.mee.gov.cn/"
weight = 4

[[params.links]]
name = "生态环境部环境规划院"
URL = "http://www.caep.org.cn/"
weight = 5

[[params.links]]
name = "中国环境科学协会"
URL = "http://www.chinacses.org/"
weight = 6

############################# social site ########################
# [params.social]
# yelp = "#"
# facebook = "#"
# twitter = "#"
# instagram = "#"
# email = "#"
# linkedin = "#"
